### ISSUE TITLE
Command 'Ultra Math Preview: Toggle Math Preview' resulted in an error (command 'umath.preview.toggleMathPreview' not found)

### ISSUE THREAD

**Issue by NgChikeung** [yfzhao20/vscode-ultra-math-preview#3]
![image](https://user-images.githubusercontent.com/16983903/162097913-b8c4e9d2-d9f3-4fb0-865b-35758d5a5abe.png)
安装后无法使用

**Comment by yfzhao20** [comment]
重启应该就好了，也有可能是插件冲突（关闭其他插件试试）。

**Comment by yfzhao20** [comment]
如果是插件冲突的问题，新版本 0.2.0 已解决，欢迎试用！

**Comment by NgChikeung** [comment]
> 如果是插件冲突的问题，新版本 0.2.0 已解决，欢迎试用！

更新后可以使用了
