### ISSUE TITLE
Preview equations in environments such as equation, align, etc.

### ISSUE THREAD

**Issue by Kcalb35** [yfzhao20/vscode-ultra-math-preview#4]
希望对equation align 等数学环境也能有预览支持。

**Comment by yfzhao20** [comment]
感谢反馈！刚刚加入equation等的支持，正在测试，还不是很稳定。稍后可以到 package 文件夹下载 0.2.1 版本的vsix文件安装。

**Comment by yfzhao20** [comment]
已更新 v0.2.1(BETA) 的安装包（在 package 文件夹），增加了equation, align, gather, displaymath等的支持，欢迎试用～

（尚未充分测试、未发布，希望没有影响其他功能🤣）

**Comment by Kcalb35** [comment]
试了一下equation align 和gather都能够成功渲染了，非常酷，为作者点赞。

不过align的对齐渲染有点问题，以下是一个例子
![image](https://user-images.githubusercontent.com/56818040/162727887-5b565988-7f41-4baf-add2-1b8df0cadbe1.png)

对应latex代码是

```latex
\begin{align}
	U_q & = -\frac{\hbar^2}{2m}\frac{\nabla^2R}{R}=-\frac{\hbar^2(x-x_0)^2}{8m\sigma^4} -\frac{\hbar^2}{2m\sigma^2}\\
	F_q & = -\nabla U_q = \frac{\hbar^2(x-x_0)}{4m\sigma^4}
\end{align}
```

**Comment by yfzhao20** [comment]
> 不过align的对齐渲染有点问题，以下是一个例子

这个问题的确存在，是因为我获取数学公式范围时，没有把 `\begin{align}` 和 `\end{align}` 本身包括进去，因此对齐就比较辣鸡🤣

由于这些环境需要包括进渲染范围，而 `$$` 以及`\\[\\]` 这些不能包括进去（mathjax的问题），因此处理起来还比较麻烦。

下个版本尝试修一下吧，最近一两周可能比较忙，暂时先凑合用了😂

**Comment by yfzhao20** [comment]
> 不过align的对齐渲染有点问题，以下是一个例子 ![image](https://user-images.githubusercontent.com/56818040/162727887-5b565988-7f41-4baf-add2-1b8df0cadbe1.png)

已更新 0.2.3 ，修复了这个问题，欢迎试用~
![image](https://user-images.githubusercontent.com/80528249/164874922-8a038366-e095-4be7-b620-e3044a2c0b26.png)

**Comment by Kcalb35** [comment]
gather和align都渲染正常了，谢谢作者！
