### ISSUE TITLE
Add support for some packages and user defined commands.

### ISSUE THREAD

**Issue by orbitoo** [yfzhao20/vscode-ultra-math-preview#6]

**Comment by yfzhao20** [comment]
Can you give me some details please? Typically MathJax cannot support all LaTeX commands. And you can use "user defined macros" to set user commands. [See Here](https://github.com/yfzhao20/vscode-ultra-math-preview#configurations--commands)

In next version maybe some MathJax packages will be added (such as `physics` package).

**Comment by orbitoo** [comment]
> Can you provide me with some details please? Typically MathJax cannot support all LaTeX commands. And you can use "user defined macros" to set user commands. [See Here](https://github.com/yfzhao20/vscode-ultra-math-preview#configurations--commands)
> 
> In next version maybe some MathJax packages will be added (such as `physics` package).

Ok, I added some to setting.json but...
I used a command provided by package "amsmath" as
```latex
\DeclareMathOperator{\Ln}{Ln}
\DeclareMathOperator{\Arctan}{Arctan}
\DeclareMathOperator{\Arg}{Arg}
```
is there a nice way to preview these?

**Comment by yfzhao20** [comment]
I'm not sure how to use `\DeclareMathOperator` in MathJax...Maybe I can try it later.

As an alternative, maybe you can try to put  `\newcommand{\Ln}{\mathop{\mathrm{Ln}}}` into `settings.json`, for it only supports `newcommand`, `renewcommand`, and `providecommand` now.

**Comment by yfzhao20** [comment]
Hmm.. Today I made a test and confirmed that `\DeclareMathOperator` is supported by MathJax.

You can put that in `settings.json` and it works:
```json
    "umath.preview.macros": [
      "\\DeclareMathOperator{\\Ln}{Ln}"
    ],
```

![image](https://user-images.githubusercontent.com/80528249/167342431-8f20e321-4af4-476e-bd77-21b2697a50e7.png)

But `\DeclareMathOperator` in your article can still not be detected and maybe I will fix the bug in next version.

**Comment by orbitoo** [comment]
> Hmm.. Today I made a test and confirmed that `\DeclareMathOperator` is supported by MathJax.
> 
> You can put that in `settings.json` and it works:
> 
> ```json
>     "umath.preview.macros": [
>       "\\DeclareMathOperator{\\Ln}{Ln}"
>     ],
> ```
> 
> ![image](https://user-images.githubusercontent.com/80528249/167342431-8f20e321-4af4-476e-bd77-21b2697a50e7.png)
> 
> But `\DeclareMathOperator` in your article can still not be detected and maybe I will fix the bug in next version.

thanks
